export const COPY = {
  welcome: {
    title: "Hi, I'm Kodu.",
    subtitle: "Let's build a peaceful place together.",
    cta: 'Start Journey',
  },
  mood: {
    header: 'How are you feeling today?',
    options: [
      { emoji: '😊', label: 'Great', key: 'great' },
      { emoji: '🙂', label: 'Okay', key: 'okay' },
      { emoji: '😰', label: 'Anxious', key: 'anxious' },
      { emoji: '😔', label: 'Low', key: 'low' },
      { emoji: '😴', label: 'Tired', key: 'drained' },
    ],
    responses: {
      great: { message: "That's wonderful 🌟", subtitle: "Let's hold onto this moment." },
      okay: { message: "That's okay 🌿", subtitle: 'Every feeling is welcome here.' },
      anxious: { message: "Take a breath with me 🌬️", subtitle: 'We can handle this together.' },
      low: { message: "I'm here with you 🌧️", subtitle: "Let's take things one step at a time." },
      drained: { message: "You don't have to do everything today 🌙", subtitle: "Let's recharge." },
    },
  },
  activities: {
    anxious: {
      title: "Let's clear the clouds.",
      type: 'breathing',
      complete: 'The clouds are getting lighter 🌤️',
    },
    low: {
      title: 'Plant a gratitude seed.',
      type: 'gratitude',
      placeholder: 'What went well today?',
      button: 'Plant Seed',
      complete: 'A flower has bloomed 🌸',
    },
    drained: {
      title: 'Rest by the campfire.',
      type: 'focus',
      complete: 'The fire is glowing bright 🔥',
    },
    okay: {
      title: 'Grow a thought into a tree.',
      type: 'journal',
      placeholder: 'What is on your mind?',
      button: 'Grow Tree',
      complete: 'A new tree stands tall 🌲',
    },
    great: {
      title: 'Capture this moment.',
      type: 'journal',
      placeholder: 'What made today good?',
      button: 'Save Moment',
      complete: 'This moment is saved 🌟',
    },
  },
  kodu: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    greetings: [
      "I'm glad you're here.",
      "Welcome back. The forest missed you.",
      "You've been working hard lately. Let's slow down for a minute.",
      "The campfire is warm today.",
      "I was thinking about you.",
    ],
    firstVisit: "Welcome home 🌲",
    checkinPrompt: 'How are you feeling?',
    memoryTemplate: 'Last time you mentioned {topic}. How is that going?',
    patternDetected: "I've noticed you've been feeling {pattern} a lot lately. Would you like to talk about it?",
    loading: ['Thinking...', 'Listening carefully...', 'Looking through the forest...'],
  },
  journey: {
    header: 'Your Journey',
    memories: 'Memories',
    milestones: 'Milestones',
    emptyMemories: 'Your memories will appear here as you grow.',
  },
  therapist: {
    title: "You don't have to carry this alone.",
    body: 'Kodu is always here to listen.\nA trained professional may be able to support you further.',
    talkButton: 'Talk to Someone',
    laterButton: 'Maybe Later',
  },
  forestEvents: {
    flowerBlooms: 'A new flower has bloomed 🌸',
    butterflyArrives: 'A butterfly has arrived 🦋',
    campfireGrows: 'Your campfire grows stronger 🔥',
    treeGrows: 'A tree grows taller 🌲',
    riverFlows: 'The river begins to flow 🌊',
  },
};
